### ISSUE TITLE
Misc. issues (audio, MCDU, PFD)

### ISSUE THREAD

**Issue by patrickfrei** [it0uchpods/A320Family#3]
Hi,

I was just flying your A320 and have found some issues:
1. Switches: When clicking on any of the switches (e.g. on the seat belt and no smoking switches) no "click" sound is audible.
2. Thrust levers: When moving the thrust levers through a detent, no "click" sound is audible.
3. Batteries: The battery voltage on the overhead panel shows 0.0.
4. Auto breaks: The auto breaks seem not to work. You can click on the switches, but no lights show up.
5. MCDU: You cannot enter anything.
6. PFD: ILS indication on PFD shows course only instead of distance in NM. See http://forum.flightgear.org/viewtopic.php?f=14&t=23736&p=250549#p250198

Would be great if you can fix them! Thank you!

Best regards,
Patrick

**Comment by it0uchpods** [comment]
Hi Patrick
1: I removed this, because I am redoing the entire overhead click spots, functions, and code. As I add the systems/switch functions, I will add the clicks. (also I have really cool different clicks for different switches :+1:  )
2: Yes, I need to find a good sound for that, then will add. The detents do work, right?
3: Because electrical system (as are 75% of systems) not done yet!
4: They don't work yet. Will be fixed.
5: MCDU will be working by V1.0. Please have your patience.
6: I am redoing the PFD speed, altitude, and other info text soon. 

Keep in mind, I am working SYSTEMS first, then cosmetics :)

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Hi Patrick,
Sorry for the delay, been busy. We are finally working on the aircraft alot.

1) the click sounds are coming very soon
2) the detent sounds have been added!
3) Fixed, the electrical system has been added. The batteries do not discharge quite yet, but the numbers do work correctly now.
4) Autobreaks are next on myagenda, they will be fixed very soon
5) MCDU initial plans have been made, and probably will begin the MCDU framework after the core systems are done
6) I will be giving the PFD instrument a major update very soon, and I will correct this!!!!

In the meantime, I am getting the FBW working, as you mentioned a while back, the aircraft didn't hold pitch/roll etc, the FBW system has now been implemented, there is a slight issue with frame rates affecting response rate, but it will be solved soon.

Kind Regards,
Josh

**Comment by patrickfrei** [comment]
Great airplane! Thank you very much!

**Comment by it0uchpods** [comment]
You're welcome!

Josh

**Comment by it0uchpods** [comment]
I'm closing this in order to keep track of further issues. Please open a new one if you have any further issues. All current ones here are on the TODO list.

J
