### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by patrickfrei** [it0uchpods/A320Family#4]
Hi,

I've just found potential issues concerning the navigation:
1. On the ND, although I've selected an ILS on NAV1, the localizer bar is not visible.
2. On the ND, I've selected a VOR DME on NAV2, but the distance is not shown. Is this really dependent on the frequency entered in the DME filed? When flying the A320neo, the DME is shown in any case.
3. The airplane seems to have a drag to the left while flying. Not sure if this is really correct.

I've attached a screenshot. Hope that helps!

Best regards,
Patrick
![navigation](https://cloud.githubusercontent.com/assets/7906165/22855317/e332b064-f07e-11e6-8ab2-dd606afdb9b5.png)

**Comment by Pakistan-1** [comment]
Do you realize that this aircraft is a work in progress (Early stages of Development) and all of these issues are known and are not going to be fixed until the core development is done ? So please stop posting new issues unlesss they are related to new updates to the aircraft thanks!

**Comment by patrickfrei** [comment]
How shall I know which issues have already been identified? I didn't find a kind of list with known issues. So, if you don't want to get any valuable feedback from the users of your aircraft I'm wondering why you don't block any postings in this section.

**Comment by it0uchpods** [comment]
Guys calm please.
The ND is from artix, and I am not at the stage yet, where I want to clone the ND into the plane. Right now it still takes from FGDATA. It doesn't show because it is talking to an FMGC, which doesn't exist yet.

When I implement the FMGC, system, I will fix this.

Also, why are you in Open Climb, with Idle Thrust? That will cause a bad!

Regards
Josh
