### ISSUE TITLE
PW engines start up too fast

### ISSUE THREAD

**Issue by legoboyvdlp** [it0uchpods/A320Family#58]
The PW1000G has an issue where startup can take up to 7 minutes. However, improvements have reduced this to about 150 seconds ( 2.5 minutes). Just slightly longer than the IAE / CFM which have about 2 min.
But still, all our engines seem to spool up a bit too fast?
And we are still missing the "AVAIL" that flashes after startup.

**Comment by it0uchpods** [comment]
OK, the issue here is if I make that number correct, then they will spoolup way to slow, this is due to JSBsim. Now you are making me wonder if I need to simulate the N1/N2 startup like I need to do with Yasim.... don't want to do it right now. I plan for this to be done by V1.0, but I can't be arsed right now. :)

AVAIL is coming soon.

**Comment by legoboyvdlp** [comment]
ok
