### ISSUE TITLE
[Question] How to setup ZFW/ZFWCG and BLOCK in FMGC

### ISSUE THREAD

**Issue by tonghuix** [it0uchpods/A320Family#62]
In "fuel and payload" dialog, it shows Gross Weight is 12987 lb, so I input 129.9 in BLOCK, it tells me "NOT ALLOWED",  and I tried FOB weight 12000lb again, still not allowed.

So how can I find the correct data of the aircraft, thank you!

**Comment by it0uchpods** [comment]
Hi,
It's not implemented quite yet -- I'll be getting it soon.

Please remember this is a WIP. Alpha software. By V1.0 everything will be working.

It does not work because it has not been programmed to accept that field yet.

Block is the fuel on board, so if you have 12000lbs, block is 12.0. Please remember my model only use LBS right now. KG will be optional later.

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
By the way, block fuel is FUEL, not gross weight :)
Check the total fuel quantity.

**Comment by it0uchpods** [comment]
Yes I know :)
